# Generated by Django 5.0.4 on 2024-04-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('tresc', models.TextField()),
                ('data_publikacji', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
