# Generated by Django 5.0.4 on 2024-05-08 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_pytanie_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odpowiedz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(max_length=5000)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odpowiedzi', to='question.pytanie')),
            ],
        ),
    ]
