# Generated by Django 5.0.4 on 2024-05-08 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_odpowiedz'),
    ]

    operations = [
        migrations.AddField(
            model_name='odpowiedz',
            name='data_odpowiedzi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
